<?php

declare(strict_types=1);

namespace CodeGuardian\Laravel\Support;

use CodeGuardian\Laravel\Analyzers\Severity;

/**
 * Builds a concise Markdown comment body for posting on a GitHub PR or GitLab MR.
 *
 * Includes a hidden marker so a poster can find and UPDATE its previous comment
 * instead of stacking new ones. Pure string building — fully unit-testable.
 */
final class PrComment
{
    public const MARKER = '<!-- codeguardian-report -->';

    /**
     * @param array<string,mixed> $results
     * @param int $maxFindings  cap the findings table (0 = no cap)
     */
    public static function body(array $results, int $maxFindings = 20): string
    {
        $summary = $results['summary'] ?? [];
        $project = (string) ($results['project_name'] ?? 'project');
        $overall = $results['overall_score'] ?? null;
        $grade   = (string) ($results['grade'] ?? '');

        $total    = (int) ($summary['total_issues'] ?? 0);
        $critical = (int) ($summary['critical'] ?? 0);
        $high     = (int) ($summary['high'] ?? 0);
        $medium   = (int) ($summary['medium'] ?? 0);
        $low      = (int) ($summary['low'] ?? 0);

        $emoji = $critical > 0 ? '🔴' : ($high > 0 ? '🟠' : ($total > 0 ? '🟡' : '🟢'));

        $out   = [];
        $out[] = self::MARKER;
        $out[] = "## {$emoji} CodeGuardian AI — `{$project}`";
        $out[] = '';

        $scoreBits = [];
        if (is_numeric($overall)) {
            $scoreBits[] = "**Quality:** {$overall}/100" . ($grade !== '' ? " (Grade {$grade})" : '');
        }
        if (isset($summary['risk_score'])) {
            $level = strtoupper((string) ($summary['risk_level'] ?? ''));
            $scoreBits[] = "**Risk:** {$summary['risk_score']}/100 ({$level})";
        }
        if ($scoreBits !== []) {
            $out[] = implode(' · ', $scoreBits);
            $out[] = '';
        }

        // Baseline diff (if present) takes the spotlight — CI cares about NEW issues.
        if (isset($summary['baseline'])) {
            $b = $summary['baseline'];
            $out[] = "**Baseline:** 🆕 {$b['new']} new · ➖ {$b['existing']} existing · ✅ {$b['fixed']} fixed";
            $out[] = '';
        }

        $out[] = '| Severity | Count |';
        $out[] = '|---|---|';
        $out[] = "| 🔴 Critical | {$critical} |";
        $out[] = "| 🟠 High | {$high} |";
        $out[] = "| 🟡 Medium | {$medium} |";
        $out[] = "| 🟢 Low | {$low} |";
        $out[] = "| **Total** | **{$total}** |";
        $out[] = '';

        $findings = self::topFindings($results, $maxFindings);
        if ($findings !== []) {
            $out[] = '<details><summary>Top findings</summary>';
            $out[] = '';
            $out[] = '| Severity | Issue | Location |';
            $out[] = '|---|---|---|';
            foreach ($findings as $f) {
                $sev   = strtoupper((string) ($f['severity'] ?? ''));
                $title = self::cell((string) ($f['title'] ?? 'Issue'));
                $file  = (string) ($f['file'] ?? '');
                $line  = (int) ($f['line_start'] ?? 0);
                $loc   = $file !== '' ? '`' . $file . ($line > 0 ? ":{$line}" : '') . '`' : '—';
                $out[] = "| {$sev} | {$title} | {$loc} |";
            }
            $out[] = '';
            $out[] = '</details>';
            $out[] = '';
        }

        $verdict = match (true) {
            ! is_numeric($overall) => 'Analysis complete.',
            $overall >= 80         => '✅ Good overall health.',
            $overall >= 60         => '🟡 Acceptable, with notable debt to schedule.',
            $overall >= 40         => '🟠 Needs attention; prioritise high-impact issues.',
            default                => '🔴 At risk; critical issues need immediate remediation.',
        };
        $out[] = $verdict;
        $out[] = '';
        $out[] = '<sub>Generated by CodeGuardian AI</sub>';

        return implode("\n", $out);
    }

    /**
     * @param array<string,mixed> $results
     * @return array<int,array<string,mixed>>
     */
    private static function topFindings(array $results, int $max): array
    {
        $findings = $results['summary']['top_findings'] ?? null;
        if (! is_array($findings) || $findings === []) {
            $findings = is_array($results['all_findings'] ?? null) ? $results['all_findings'] : [];
            usort($findings, fn($a, $b) =>
                (Severity::ORDER[Severity::clamp($a['severity'] ?? '')] ?? 4)
                <=> (Severity::ORDER[Severity::clamp($b['severity'] ?? '')] ?? 4)
            );
        }

        $findings = array_values($findings);
        if ($max > 0 && count($findings) > $max) {
            $findings = array_slice($findings, 0, $max);
        }

        return $findings;
    }

    private static function cell(string $value): string
    {
        return trim(str_replace(['|', "\r", "\n"], ['\\|', ' ', ' '], $value));
    }
}
